//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the rqt_tutorial package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __rqt_tutorial__RQT_TUTORIALCONFIG_H__
#define __rqt_tutorial__RQT_TUTORIALCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace rqt_tutorial
{
  class rqt_tutorialConfigStatics;

  class rqt_tutorialConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(rqt_tutorialConfig &config, const rqt_tutorialConfig &max, const rqt_tutorialConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const rqt_tutorialConfig &config1, const rqt_tutorialConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, rqt_tutorialConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const rqt_tutorialConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, rqt_tutorialConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const rqt_tutorialConfig &config) const = 0;
      virtual void getValue(const rqt_tutorialConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T rqt_tutorialConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T rqt_tutorialConfig::* field;

      virtual void clamp(rqt_tutorialConfig &config, const rqt_tutorialConfig &max, const rqt_tutorialConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const rqt_tutorialConfig &config1, const rqt_tutorialConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, rqt_tutorialConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const rqt_tutorialConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, rqt_tutorialConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const rqt_tutorialConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const rqt_tutorialConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, rqt_tutorialConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, rqt_tutorialConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<rqt_tutorialConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(rqt_tutorialConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);


      }
    }

    

    bool state;
    std::string name;

    class A_SPEED
{
  public:
    A_SPEED()
    {
      state = true;
      name = "A_speed";
    }

    void setParams(rqt_tutorialConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("speed_A"==(*_i)->name){speed_A = boost::any_cast<double>(val);}
        if("speed_B"==(*_i)->name){speed_B = boost::any_cast<double>(val);}
      }
    }

    double speed_A;
double speed_B;

    bool state;
    std::string name;

    
}a_speed;

class B_POSITION
{
  public:
    B_POSITION()
    {
      state = true;
      name = "B_position";
    }

    void setParams(rqt_tutorialConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("X_position"==(*_i)->name){X_position = boost::any_cast<double>(val);}
        if("Y_position"==(*_i)->name){Y_position = boost::any_cast<double>(val);}
      }
    }

    double X_position;
double Y_position;

    bool state;
    std::string name;

    
}b_position;

}groups;



//#line 30 "/home/lby/tutorial_ws/src/rqt_tutorial/cfg/rqt_tutorial.cfg"
      double speed_A;
//#line 31 "/home/lby/tutorial_ws/src/rqt_tutorial/cfg/rqt_tutorial.cfg"
      double speed_B;
//#line 42 "/home/lby/tutorial_ws/src/rqt_tutorial/cfg/rqt_tutorial.cfg"
      double X_position;
//#line 43 "/home/lby/tutorial_ws/src/rqt_tutorial/cfg/rqt_tutorial.cfg"
      double Y_position;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("rqt_tutorialConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (size_t i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (size_t i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (size_t i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (size_t i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const rqt_tutorialConfig &__max__ = __getMax__();
      const rqt_tutorialConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const rqt_tutorialConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const rqt_tutorialConfig &__getDefault__();
    static const rqt_tutorialConfig &__getMax__();
    static const rqt_tutorialConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const rqt_tutorialConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void rqt_tutorialConfig::ParamDescription<std::string>::clamp(rqt_tutorialConfig &config, const rqt_tutorialConfig &max, const rqt_tutorialConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class rqt_tutorialConfigStatics
  {
    friend class rqt_tutorialConfig;

    rqt_tutorialConfigStatics()
    {
rqt_tutorialConfig::GroupDescription<rqt_tutorialConfig::DEFAULT, rqt_tutorialConfig> Default("Default", "", 0, 0, true, &rqt_tutorialConfig::groups);
rqt_tutorialConfig::GroupDescription<rqt_tutorialConfig::DEFAULT::A_SPEED, rqt_tutorialConfig::DEFAULT> A_speed("A_speed", "tab", 0, 1, true, &rqt_tutorialConfig::DEFAULT::a_speed);
//#line 30 "/home/lby/tutorial_ws/src/rqt_tutorial/cfg/rqt_tutorial.cfg"
      __min__.speed_A = 0.0;
//#line 30 "/home/lby/tutorial_ws/src/rqt_tutorial/cfg/rqt_tutorial.cfg"
      __max__.speed_A = 10.0;
//#line 30 "/home/lby/tutorial_ws/src/rqt_tutorial/cfg/rqt_tutorial.cfg"
      __default__.speed_A = 1.0;
//#line 30 "/home/lby/tutorial_ws/src/rqt_tutorial/cfg/rqt_tutorial.cfg"
      A_speed.abstract_parameters.push_back(rqt_tutorialConfig::AbstractParamDescriptionConstPtr(new rqt_tutorialConfig::ParamDescription<double>("speed_A", "double", 0, "速度A", "", &rqt_tutorialConfig::speed_A)));
//#line 30 "/home/lby/tutorial_ws/src/rqt_tutorial/cfg/rqt_tutorial.cfg"
      __param_descriptions__.push_back(rqt_tutorialConfig::AbstractParamDescriptionConstPtr(new rqt_tutorialConfig::ParamDescription<double>("speed_A", "double", 0, "速度A", "", &rqt_tutorialConfig::speed_A)));
//#line 31 "/home/lby/tutorial_ws/src/rqt_tutorial/cfg/rqt_tutorial.cfg"
      __min__.speed_B = 0.0;
//#line 31 "/home/lby/tutorial_ws/src/rqt_tutorial/cfg/rqt_tutorial.cfg"
      __max__.speed_B = 10.0;
//#line 31 "/home/lby/tutorial_ws/src/rqt_tutorial/cfg/rqt_tutorial.cfg"
      __default__.speed_B = 2.0;
//#line 31 "/home/lby/tutorial_ws/src/rqt_tutorial/cfg/rqt_tutorial.cfg"
      A_speed.abstract_parameters.push_back(rqt_tutorialConfig::AbstractParamDescriptionConstPtr(new rqt_tutorialConfig::ParamDescription<double>("speed_B", "double", 0, "速度B", "", &rqt_tutorialConfig::speed_B)));
//#line 31 "/home/lby/tutorial_ws/src/rqt_tutorial/cfg/rqt_tutorial.cfg"
      __param_descriptions__.push_back(rqt_tutorialConfig::AbstractParamDescriptionConstPtr(new rqt_tutorialConfig::ParamDescription<double>("speed_B", "double", 0, "速度B", "", &rqt_tutorialConfig::speed_B)));
//#line 125 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      A_speed.convertParams();
//#line 125 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(rqt_tutorialConfig::AbstractGroupDescriptionConstPtr(new rqt_tutorialConfig::GroupDescription<rqt_tutorialConfig::DEFAULT::A_SPEED, rqt_tutorialConfig::DEFAULT>(A_speed)));
//#line 125 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(rqt_tutorialConfig::AbstractGroupDescriptionConstPtr(new rqt_tutorialConfig::GroupDescription<rqt_tutorialConfig::DEFAULT::A_SPEED, rqt_tutorialConfig::DEFAULT>(A_speed)));
rqt_tutorialConfig::GroupDescription<rqt_tutorialConfig::DEFAULT::B_POSITION, rqt_tutorialConfig::DEFAULT> B_position("B_position", "tab", 0, 2, true, &rqt_tutorialConfig::DEFAULT::b_position);
//#line 42 "/home/lby/tutorial_ws/src/rqt_tutorial/cfg/rqt_tutorial.cfg"
      __min__.X_position = -10.0;
//#line 42 "/home/lby/tutorial_ws/src/rqt_tutorial/cfg/rqt_tutorial.cfg"
      __max__.X_position = 10.0;
//#line 42 "/home/lby/tutorial_ws/src/rqt_tutorial/cfg/rqt_tutorial.cfg"
      __default__.X_position = 0.0;
//#line 42 "/home/lby/tutorial_ws/src/rqt_tutorial/cfg/rqt_tutorial.cfg"
      B_position.abstract_parameters.push_back(rqt_tutorialConfig::AbstractParamDescriptionConstPtr(new rqt_tutorialConfig::ParamDescription<double>("X_position", "double", 0, "X坐标", "", &rqt_tutorialConfig::X_position)));
//#line 42 "/home/lby/tutorial_ws/src/rqt_tutorial/cfg/rqt_tutorial.cfg"
      __param_descriptions__.push_back(rqt_tutorialConfig::AbstractParamDescriptionConstPtr(new rqt_tutorialConfig::ParamDescription<double>("X_position", "double", 0, "X坐标", "", &rqt_tutorialConfig::X_position)));
//#line 43 "/home/lby/tutorial_ws/src/rqt_tutorial/cfg/rqt_tutorial.cfg"
      __min__.Y_position = -10.0;
//#line 43 "/home/lby/tutorial_ws/src/rqt_tutorial/cfg/rqt_tutorial.cfg"
      __max__.Y_position = 10.0;
//#line 43 "/home/lby/tutorial_ws/src/rqt_tutorial/cfg/rqt_tutorial.cfg"
      __default__.Y_position = 0.0;
//#line 43 "/home/lby/tutorial_ws/src/rqt_tutorial/cfg/rqt_tutorial.cfg"
      B_position.abstract_parameters.push_back(rqt_tutorialConfig::AbstractParamDescriptionConstPtr(new rqt_tutorialConfig::ParamDescription<double>("Y_position", "double", 0, "Y坐标", "", &rqt_tutorialConfig::Y_position)));
//#line 43 "/home/lby/tutorial_ws/src/rqt_tutorial/cfg/rqt_tutorial.cfg"
      __param_descriptions__.push_back(rqt_tutorialConfig::AbstractParamDescriptionConstPtr(new rqt_tutorialConfig::ParamDescription<double>("Y_position", "double", 0, "Y坐标", "", &rqt_tutorialConfig::Y_position)));
//#line 125 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      B_position.convertParams();
//#line 125 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.groups.push_back(rqt_tutorialConfig::AbstractGroupDescriptionConstPtr(new rqt_tutorialConfig::GroupDescription<rqt_tutorialConfig::DEFAULT::B_POSITION, rqt_tutorialConfig::DEFAULT>(B_position)));
//#line 125 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(rqt_tutorialConfig::AbstractGroupDescriptionConstPtr(new rqt_tutorialConfig::GroupDescription<rqt_tutorialConfig::DEFAULT::B_POSITION, rqt_tutorialConfig::DEFAULT>(B_position)));
//#line 247 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 247 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(rqt_tutorialConfig::AbstractGroupDescriptionConstPtr(new rqt_tutorialConfig::GroupDescription<rqt_tutorialConfig::DEFAULT, rqt_tutorialConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<rqt_tutorialConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<rqt_tutorialConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<rqt_tutorialConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    rqt_tutorialConfig __max__;
    rqt_tutorialConfig __min__;
    rqt_tutorialConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const rqt_tutorialConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static rqt_tutorialConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &rqt_tutorialConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const rqt_tutorialConfig &rqt_tutorialConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const rqt_tutorialConfig &rqt_tutorialConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const rqt_tutorialConfig &rqt_tutorialConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<rqt_tutorialConfig::AbstractParamDescriptionConstPtr> &rqt_tutorialConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<rqt_tutorialConfig::AbstractGroupDescriptionConstPtr> &rqt_tutorialConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const rqt_tutorialConfigStatics *rqt_tutorialConfig::__get_statics__()
  {
    const static rqt_tutorialConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = rqt_tutorialConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __RQT_TUTORIALRECONFIGURATOR_H__
